# Development-specific overrides
version: '3.8'

services:
  backend:
    build:
      context: ./langgraph-api
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      # Mount entire backend directory for full development
      - ./langgraph-api:/app
      # Exclude virtual environment from host mount
      - /app/.venv
    environment:
      - API_ENV=development
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      # Mount entire frontend directory
      - ./client:/app
      # Exclude node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development